package org.jboss.optaplanner.controller.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-05-11T11:07:59.338+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://server.service.optaplanner.jboss.org/", name = "OptaPlannerWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface OptaPlannerWebService {

    @RequestWrapper(localName = "pauseTask", targetNamespace = "http://server.service.optaplanner.jboss.org/", className = "org.jboss.optaplanner.service.server.PauseTask")
    @WebMethod
    @ResponseWrapper(localName = "pauseTaskResponse", targetNamespace = "http://server.service.optaplanner.jboss.org/", className = "org.jboss.optaplanner.service.server.PauseTaskResponse")
    public void pauseTask(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    ) throws Exception_Exception;

    @RequestWrapper(localName = "startTask", targetNamespace = "http://server.service.optaplanner.jboss.org/", className = "org.jboss.optaplanner.service.server.StartTask")
    @WebMethod
    @ResponseWrapper(localName = "startTaskResponse", targetNamespace = "http://server.service.optaplanner.jboss.org/", className = "org.jboss.optaplanner.service.server.StartTaskResponse")
    public void startTask(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createTask", targetNamespace = "http://server.service.optaplanner.jboss.org/", className = "org.jboss.optaplanner.service.server.CreateTask")
    @WebMethod
    @ResponseWrapper(localName = "createTaskResponse", targetNamespace = "http://server.service.optaplanner.jboss.org/", className = "org.jboss.optaplanner.service.server.CreateTaskResponse")
    public long createTask(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws Exception_Exception;
}
