package org.jboss.optaplanner.controller.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-05-11T11:07:59.361+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "OptaPlannerWebServiceService", 
                  wsdlLocation = "http://localhost:8080/optaplanner-service/OptaPlannerWebService?wsdl",
                  targetNamespace = "http://server.service.optaplanner.jboss.org/") 
public class OptaPlannerWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.service.optaplanner.jboss.org/", "OptaPlannerWebServiceService");
    public final static QName OptaPlannerWebServicePort = new QName("http://server.service.optaplanner.jboss.org/", "OptaPlannerWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/optaplanner-service/OptaPlannerWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OptaPlannerWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/optaplanner-service/OptaPlannerWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OptaPlannerWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OptaPlannerWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OptaPlannerWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OptaPlannerWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OptaPlannerWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OptaPlannerWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns OptaPlannerWebService
     */
    @WebEndpoint(name = "OptaPlannerWebServicePort")
    public OptaPlannerWebService getOptaPlannerWebServicePort() {
        return super.getPort(OptaPlannerWebServicePort, OptaPlannerWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OptaPlannerWebService
     */
    @WebEndpoint(name = "OptaPlannerWebServicePort")
    public OptaPlannerWebService getOptaPlannerWebServicePort(WebServiceFeature... features) {
        return super.getPort(OptaPlannerWebServicePort, OptaPlannerWebService.class, features);
    }

}
